-- Generated 2026-05-05. Apply in order: common/odds schemas first, then sport schemas.

CREATE TABLE [nfl].[ftn_charting] (
    [ftn_game_id] INT,
    [game_id] VARCHAR(MAX),
    [season] INT,
    [week] INT,
    [ftn_play_id] INT,
    [nflverse_play_id] INT,
    [starting_hash] VARCHAR(MAX),
    [qb_location] VARCHAR(MAX),
    [n_offense_backfield] FLOAT,
    [n_defense_box] INT,
    [is_no_huddle] BIT,
    [is_motion] BIT,
    [is_play_action] BIT,
    [is_screen_pass] BIT,
    [is_rpo] BIT,
    [is_trick_play] FLOAT,
    [is_qb_out_of_pocket] BIT,
    [is_interception_worthy] BIT,
    [is_throw_away] BIT,
    [read_thrown] VARCHAR(MAX),
    [is_catchable_ball] BIT,
    [is_contested_ball] BIT,
    [is_created_reception] BIT,
    [is_drop] BIT,
    [is_qb_sneak] BIT,
    [n_blitzers] INT,
    [n_pass_rushers] INT,
    [is_qb_fault_sack] BIT,
    [date_pulled] DATETIME,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL
);

CREATE TABLE [nfl].[games] (
    [game_id] VARCHAR(MAX),
    [season] INT,
    [game_type] VARCHAR(MAX),
    [week] INT,
    [game_date] DATE,
    [weekday] VARCHAR(MAX),
    [gametime] VARCHAR(MAX),
    [away_team] VARCHAR(MAX),
    [away_score] INT,
    [home_team] VARCHAR(MAX),
    [home_score] INT,
    [location] VARCHAR(MAX),
    [result] INT,
    [total] INT,
    [overtime] INT,
    [old_game_id] BIGINT,
    [gsis_id] INT,
    [nfl_detail_id] FLOAT,
    [pfr_game_id] VARCHAR(MAX),
    [pff_game_id] FLOAT,
    [espn_id] BIGINT,
    [ftn_id] FLOAT,
    [away_rest_days] INT,
    [home_rest_days] INT,
    [away_moneyline] INT,
    [home_moneyline] INT,
    [spread_line] FLOAT,
    [away_spread_odds] INT,
    [home_spread_odds] INT,
    [total_line] FLOAT,
    [under_odds] INT,
    [over_odds] INT,
    [is_div_game] INT,
    [roof] VARCHAR(MAX),
    [surface] VARCHAR(MAX),
    [temp_f] FLOAT,
    [wind_mph] FLOAT,
    [away_qb_gsis_id] VARCHAR(MAX),
    [home_qb_gsis_id] VARCHAR(MAX),
    [away_qb_name] VARCHAR(MAX),
    [home_qb_name] VARCHAR(MAX),
    [away_coach] VARCHAR(MAX),
    [home_coach] VARCHAR(MAX),
    [referee] VARCHAR(MAX),
    [stadium_id] VARCHAR(MAX),
    [stadium_name] VARCHAR(MAX),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL
);

CREATE TABLE [nfl].[pff_dim_games] (
    [game_id_pff] INT NOT NULL,
    [season] SMALLINT NOT NULL,
    [season_type] VARCHAR(10) NOT NULL,
    [game_date] DATETIME2,
    [game_slug] VARCHAR(100),
    [away_team_id] INT,
    [home_team_id] INT,
    [is_all_star] BIT,
    [is_in_progress] BIT,
    [is_over] BIT,
    [is_postseason] BIT,
    [is_preseason] BIT,
    [is_regular_season] BIT,
    [has_stats] BIT,
    [week_id_pff] INT,
    [week_name] VARCHAR(30),
    [week_abbreviation] VARCHAR(5),
    [week_display_order] TINYINT,
    [week_index] TINYINT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_dim_games] PRIMARY KEY ([game_id_pff])
);

CREATE TABLE [nfl].[pff_dim_players] (
    [player_id_pff] INT NOT NULL,
    [player_name] VARCHAR(60) NOT NULL,
    [player_slug] VARCHAR(80),
    [position] VARCHAR(5),
    [grade_position] VARCHAR(5),
    [display_position] VARCHAR(10),
    [unit] VARCHAR(15),
    [status] VARCHAR(5),
    [jersey_number] TINYINT,
    [age] DECIMAL(4,1),
    [height_raw] SMALLINT,
    [weight_lbs] SMALLINT,
    [speed] VARCHAR(10),
    [college] VARCHAR(60),
    [draft_season] SMALLINT,
    [draft_round] TINYINT,
    [draft_selection] TINYINT,
    [draft_league] VARCHAR(5),
    [draft_type] VARCHAR(5),
    [draft_team_id_pff] INT,
    [current_eligible_year] SMALLINT,
    [meets_snap_minimum] BIT,
    [team_id_pff] INT,
    [team_name] VARCHAR(5),
    [team_slug] VARCHAR(40),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_dim_players] PRIMARY KEY ([player_id_pff])
);

CREATE TABLE [nfl].[pff_dim_teams] (
    [team_id_pff] INT NOT NULL,
    [team_city] VARCHAR(30) NOT NULL,
    [team_name] VARCHAR(5) NOT NULL,
    [team_nickname] VARCHAR(20) NOT NULL,
    [team_abbreviation] VARCHAR(5) NOT NULL,
    [nflverse_team] VARCHAR(3),
    [conference] VARCHAR(5) NOT NULL,
    [division] VARCHAR(15) NOT NULL,
    [color_primary] VARCHAR(10),
    [color_secondary] VARCHAR(10),
    [color_tertiary] VARCHAR(10),
    [color_dark] VARCHAR(10),
    [color_light] VARCHAR(10),
    [color_background] VARCHAR(10),
    [color_foreground] VARCHAR(10),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_dim_teams] PRIMARY KEY ([team_id_pff])
);

CREATE TABLE [nfl].[pff_dim_weeks] (
    [week_id_pff] INT NOT NULL,
    [week_name] VARCHAR(30) NOT NULL,
    [week_abbreviation] VARCHAR(5),
    [display_order] TINYINT NOT NULL,
    [league] VARCHAR(5),
    [is_regular_season] BIT NOT NULL,
    [is_preseason] BIT NOT NULL,
    [is_postseason] BIT NOT NULL,
    [is_all_star] BIT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_dim_weeks] PRIMARY KEY ([week_id_pff])
);

CREATE TABLE [nfl].[pff_fantasy_passing] (
    [pff_fp_id] INT NOT NULL,
    [season] SMALLINT NOT NULL,
    [week_id_pff] INT NOT NULL,
    [player_id_pff] INT NOT NULL,
    [player_name] VARCHAR(60),
    [team_id_pff] INT,
    [team_name] VARCHAR(5),
    [refresh_timestamp] DATETIME2,
    [fantasy_points] DECIMAL(6,1),
    [pts_per_dropback] DECIMAL(5,2),
    [attempts] SMALLINT,
    [completions] SMALLINT,
    [completion_pct_no_drops] DECIMAL(5,1),
    [avg_depth_of_target] DECIMAL(5,2),
    [dropbacks] SMALLINT,
    [drops] TINYINT,
    [interceptions] TINYINT,
    [sacks] TINYINT,
    [touchdowns] TINYINT,
    [yards] SMALLINT,
    [pass_td_40_plus] TINYINT,
    [pass_td_50_plus] TINYINT,
    [pass_300_yard_game] TINYINT,
    [ez_attempts] TINYINT,
    [ez_interceptions] TINYINT,
    [ez_target_pct] DECIMAL(5,1),
    [ez_td_pct] DECIMAL(5,1),
    [ez_touchdowns] TINYINT,
    [rush_carries] SMALLINT,
    [rush_yards] SMALLINT,
    [rush_tds] TINYINT,
    [rush_td_40_plus] TINYINT,
    [rz_rush_carries] TINYINT,
    [rz_rush_pct] DECIMAL(5,1),
    [rz_rush_tds] TINYINT,
    [i5_rush_carries] TINYINT,
    [i5_rush_pct] DECIMAL(5,1),
    [i5_rush_tds] TINYINT,
    [fumbles] TINYINT,
    [pat_attempts] TINYINT,
    [pat_conversions] TINYINT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_fantasy_passing] PRIMARY KEY ([pff_fp_id])
);
CREATE UNIQUE INDEX [UQ_nfl_pff_fp_key] ON [nfl].[pff_fantasy_passing] ([season], [week_id_pff], [player_id_pff]);

CREATE TABLE [nfl].[pff_fantasy_receiving] (
    [pff_fr_id] INT NOT NULL,
    [season] SMALLINT NOT NULL,
    [week_id_pff] INT NOT NULL,
    [player_id_pff] INT NOT NULL,
    [player_name] VARCHAR(60),
    [position] VARCHAR(10),
    [team_id_pff] INT,
    [team_name] VARCHAR(5),
    [refresh_timestamp] DATETIME2,
    [fantasy_points] DECIMAL(6,1),
    [pts_per_snap] DECIMAL(6,2),
    [pts_per_touch] DECIMAL(6,2),
    [snaps] SMALLINT,
    [routes] SMALLINT,
    [targets] SMALLINT,
    [receptions] SMALLINT,
    [receiving_yards] SMALLINT,
    [receiving_tds] TINYINT,
    [yards_after_catch] SMALLINT,
    [yac] SMALLINT,
    [avg_depth_of_target] DECIMAL(5,2),
    [total_air_yards] SMALLINT,
    [catch_pct] DECIMAL(5,1),
    [rec_drops] TINYINT,
    [receptions_40_plus] TINYINT,
    [rec_td_40_plus] TINYINT,
    [rec_100_yard_game] TINYINT,
    [yprr] DECIMAL(5,2),
    [yards_per_reception] DECIMAL(5,2),
    [ez_rec_targets] TINYINT,
    [ez_rec_receptions] TINYINT,
    [ez_rec_target_pct] DECIMAL(5,1),
    [ez_rec_catch_pct] DECIMAL(5,1),
    [ez_rec_td_pct] DECIMAL(5,1),
    [ez_rec_touchdowns] TINYINT,
    [rz_rec_targets] TINYINT,
    [rz_rec_receptions] TINYINT,
    [rz_rec_target_pct] DECIMAL(5,1),
    [rz_rec_catch_pct] DECIMAL(5,1),
    [rz_rec_td_pct] DECIMAL(5,1),
    [rz_rec_touchdowns] TINYINT,
    [rush_carries] SMALLINT,
    [rush_yards] SMALLINT,
    [rush_tds] TINYINT,
    [rush_40_plus] TINYINT,
    [rush_td_40_plus] TINYINT,
    [rush_yards_after_contact] SMALLINT,
    [rush_100_yard_game] TINYINT,
    [yards_per_carry] DECIMAL(5,2),
    [yards_per_touch] DECIMAL(5,2),
    [total_touches] SMALLINT,
    [rz_rush_carries] TINYINT,
    [rz_rush_pct] DECIMAL(5,1),
    [rz_rush_td_pct] DECIMAL(5,1),
    [rz_rush_tds] TINYINT,
    [i5_rush_carries] TINYINT,
    [i5_rush_pct] DECIMAL(5,1),
    [i5_rush_td_pct] DECIMAL(5,1),
    [i5_rush_tds] TINYINT,
    [fumbles] TINYINT,
    [pat_attempts] TINYINT,
    [pat_conversions] TINYINT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_fantasy_receiving] PRIMARY KEY ([pff_fr_id])
);
CREATE UNIQUE INDEX [UQ_nfl_pff_fr_key] ON [nfl].[pff_fantasy_receiving] ([season], [week_id_pff], [player_id_pff]);

CREATE TABLE [nfl].[pff_offense] (
    [pff_offense_id] INT NOT NULL,
    [game_id_pff] INT NOT NULL,
    [player_id_pff] INT NOT NULL,
    [season] SMALLINT NOT NULL,
    [week_id_pff] INT NOT NULL,
    [player_name] VARCHAR(60),
    [position] VARCHAR(5),
    [roster_status] VARCHAR(5),
    [jersey_number] TINYINT,
    [franchise_id_pff] INT,
    [refresh_timestamp] DATETIME2,
    [grade_offense] DECIMAL(5,1),
    [grade_pass] DECIMAL(5,1),
    [grade_pass_block] DECIMAL(5,1),
    [grade_pass_route] DECIMAL(5,1),
    [grade_run] DECIMAL(5,1),
    [grade_run_block] DECIMAL(5,1),
    [grade_hands_fumble] DECIMAL(5,1),
    [grade_offense_penalty] DECIMAL(5,1),
    [declined_penalties] TINYINT,
    [penalties] TINYINT,
    [snaps_pass] SMALLINT,
    [snaps_pass_block] SMALLINT,
    [snaps_pass_route] SMALLINT,
    [snaps_run] SMALLINT,
    [snaps_run_block] SMALLINT,
    [snaps_total] SMALLINT,
    [snaps_total_pass] SMALLINT,
    [snaps_total_run] SMALLINT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_offense] PRIMARY KEY ([pff_offense_id])
);
CREATE UNIQUE INDEX [UQ_nfl_pff_offense_key] ON [nfl].[pff_offense] ([game_id_pff], [player_id_pff]);

CREATE TABLE [nfl].[pff_passing] (
    [pff_passing_id] INT NOT NULL,
    [game_id_pff] INT NOT NULL,
    [player_id_pff] INT NOT NULL,
    [season] SMALLINT NOT NULL,
    [week_id_pff] INT NOT NULL,
    [player_name] VARCHAR(60),
    [position] VARCHAR(5),
    [roster_status] VARCHAR(5),
    [jersey_number] VARCHAR(5),
    [franchise_id_pff] INT,
    [refresh_timestamp] DATETIME2,
    [grade_offense] DECIMAL(5,1),
    [grade_pass] DECIMAL(5,1),
    [grade_run] DECIMAL(5,1),
    [grade_hands_fumble] DECIMAL(5,1),
    [accuracy_pct] DECIMAL(5,1),
    [aimed_passes] SMALLINT,
    [attempts] SMALLINT,
    [avg_depth_of_target] DECIMAL(5,2),
    [avg_time_to_throw] DECIMAL(4,2),
    [bats] TINYINT,
    [big_time_throws] TINYINT,
    [btt_rate] DECIMAL(5,2),
    [completion_pct] DECIMAL(5,1),
    [completions] SMALLINT,
    [dropbacks] SMALLINT,
    [drops] TINYINT,
    [drop_rate] DECIMAL(5,2),
    [first_downs] SMALLINT,
    [hit_as_threw] TINYINT,
    [interceptions] TINYINT,
    [passing_snaps] SMALLINT,
    [penalties] TINYINT,
    [declined_penalties] TINYINT,
    [pressures_faced] TINYINT,
    [pressure_to_sack_rate] DECIMAL(5,1),
    [qb_rating] DECIMAL(5,1),
    [sacks] TINYINT,
    [sack_pct] DECIMAL(5,2),
    [scrambles] TINYINT,
    [spikes] TINYINT,
    [thrown_aways] TINYINT,
    [touchdowns] TINYINT,
    [turnover_worthy_plays] TINYINT,
    [twp_rate] DECIMAL(5,2),
    [yards] SMALLINT,
    [ypa] DECIMAL(5,2),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_passing] PRIMARY KEY ([pff_passing_id])
);
CREATE UNIQUE INDEX [UQ_nfl_pff_passing_key] ON [nfl].[pff_passing] ([game_id_pff], [player_id_pff]);

CREATE TABLE [nfl].[pff_receiving] (
    [pff_receiving_id] INT NOT NULL,
    [game_id_pff] INT NOT NULL,
    [player_id_pff] INT NOT NULL,
    [season] SMALLINT NOT NULL,
    [week_id_pff] INT NOT NULL,
    [player_name] VARCHAR(60),
    [position] VARCHAR(10),
    [roster_status] VARCHAR(5),
    [jersey_number] TINYINT,
    [franchise_id_pff] INT,
    [refresh_timestamp] DATETIME2,
    [grade_offense] DECIMAL(5,1),
    [grade_pass_route] DECIMAL(5,1),
    [grade_pass_block] DECIMAL(5,1),
    [grade_hands_drop] DECIMAL(5,1),
    [grade_hands_fumble] DECIMAL(5,1),
    [avg_depth_of_target] DECIMAL(5,2),
    [avoided_tackles] TINYINT,
    [catch_pct] DECIMAL(5,1),
    [contested_catch_rate] DECIMAL(5,1),
    [contested_receptions] TINYINT,
    [contested_targets] TINYINT,
    [declined_penalties] TINYINT,
    [drop_rate] DECIMAL(5,2),
    [drops] TINYINT,
    [first_downs] SMALLINT,
    [fumbles] TINYINT,
    [inline_rate] DECIMAL(5,2),
    [inline_snaps] SMALLINT,
    [longest_reception] SMALLINT,
    [pass_block_rate] DECIMAL(5,2),
    [pass_blocks] SMALLINT,
    [pass_plays] SMALLINT,
    [penalties] TINYINT,
    [receptions] SMALLINT,
    [route_rate] DECIMAL(5,1),
    [routes] SMALLINT,
    [slot_rate] DECIMAL(5,1),
    [slot_snaps] SMALLINT,
    [wide_rate] DECIMAL(5,1),
    [wide_snaps] SMALLINT,
    [targeted_qb_rating] DECIMAL(5,1),
    [targets] SMALLINT,
    [touchdowns] TINYINT,
    [yards] SMALLINT,
    [yards_after_catch] SMALLINT,
    [yac_per_reception] DECIMAL(5,2),
    [yards_per_reception] DECIMAL(5,2),
    [yprr] DECIMAL(5,2),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_receiving] PRIMARY KEY ([pff_receiving_id])
);
CREATE UNIQUE INDEX [UQ_nfl_pff_receiving_key] ON [nfl].[pff_receiving] ([game_id_pff], [player_id_pff]);

CREATE TABLE [nfl].[pff_rushing] (
    [pff_rushing_id] INT NOT NULL,
    [game_id_pff] INT NOT NULL,
    [player_id_pff] INT NOT NULL,
    [season] SMALLINT NOT NULL,
    [week_id_pff] INT NOT NULL,
    [player_name] VARCHAR(60),
    [position] VARCHAR(5),
    [roster_status] VARCHAR(5),
    [jersey_number] TINYINT,
    [franchise_id_pff] INT,
    [refresh_timestamp] DATETIME2,
    [grade_offense] DECIMAL(5,1),
    [grade_run] DECIMAL(5,1),
    [grade_pass] DECIMAL(5,1),
    [grade_pass_block] DECIMAL(5,1),
    [grade_pass_route] DECIMAL(5,1),
    [grade_run_block] DECIMAL(5,1),
    [grade_hands_fumble] DECIMAL(5,1),
    [grade_offense_penalty] DECIMAL(5,1),
    [attempts] SMALLINT,
    [avoided_tackles] TINYINT,
    [breakaway_attempts] TINYINT,
    [breakaway_pct] DECIMAL(5,1),
    [breakaway_yards] SMALLINT,
    [declined_penalties] TINYINT,
    [designed_yards] SMALLINT,
    [drops] TINYINT,
    [elu_recv_mtf] TINYINT,
    [elu_rush_mtf] TINYINT,
    [elu_yco] SMALLINT,
    [elusive_rating] DECIMAL(5,1),
    [explosive_runs] TINYINT,
    [first_downs] SMALLINT,
    [fumbles] TINYINT,
    [gap_attempts] SMALLINT,
    [zone_attempts] SMALLINT,
    [longest_run] SMALLINT,
    [penalties] TINYINT,
    [rec_yards] SMALLINT,
    [receptions] TINYINT,
    [routes] TINYINT,
    [run_plays] SMALLINT,
    [scramble_yards] SMALLINT,
    [scrambles] TINYINT,
    [targets] TINYINT,
    [total_touches] SMALLINT,
    [touchdowns] TINYINT,
    [yards] SMALLINT,
    [yards_after_contact] SMALLINT,
    [yco_per_attempt] DECIMAL(4,2),
    [ypa] DECIMAL(4,2),
    [yprr] DECIMAL(5,2),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pff_rushing] PRIMARY KEY ([pff_rushing_id])
);
CREATE UNIQUE INDEX [UQ_nfl_pff_rushing_key] ON [nfl].[pff_rushing] ([game_id_pff], [player_id_pff]);

CREATE TABLE [nfl].[player_game_stats] (
    [player_gsis_id] VARCHAR(MAX),
    [player_name] VARCHAR(MAX),
    [player_display_name] VARCHAR(MAX),
    [position] VARCHAR(MAX),
    [position_group] VARCHAR(MAX),
    [season] INT,
    [week] INT,
    [season_type] VARCHAR(MAX),
    [game_id] VARCHAR(MAX),
    [team] VARCHAR(MAX),
    [opponent_team] VARCHAR(MAX),
    [completions] INT,
    [attempts] INT,
    [passing_yards] INT,
    [passing_tds] INT,
    [passing_interceptions] INT,
    [sacks_suffered] INT,
    [sack_yards_lost] INT,
    [sack_fumbles] INT,
    [sack_fumbles_lost] INT,
    [passing_air_yards] INT,
    [passing_yards_after_catch] INT,
    [passing_first_downs] INT,
    [passing_epa] FLOAT,
    [passing_cpoe] FLOAT,
    [passing_2pt_conversions] INT,
    [pacr] FLOAT,
    [carries] INT,
    [rushing_yards] INT,
    [rushing_tds] INT,
    [rushing_fumbles] INT,
    [rushing_fumbles_lost] INT,
    [rushing_first_downs] INT,
    [rushing_epa] FLOAT,
    [rushing_2pt_conversions] INT,
    [receptions] INT,
    [targets] INT,
    [receiving_yards] INT,
    [receiving_tds] INT,
    [receiving_fumbles] INT,
    [receiving_fumbles_lost] INT,
    [receiving_air_yards] INT,
    [receiving_yards_after_catch] INT,
    [receiving_first_downs] INT,
    [receiving_epa] FLOAT,
    [receiving_2pt_conversions] INT,
    [racr] FLOAT,
    [target_share] FLOAT,
    [air_yards_share] FLOAT,
    [wopr] FLOAT,
    [special_teams_tds] INT,
    [def_tackles_solo] INT,
    [def_tackles_with_assist] INT,
    [def_tackle_assists] INT,
    [def_tackles_for_loss] INT,
    [def_tackles_for_loss_yards] INT,
    [def_fumbles_forced] INT,
    [def_sacks] FLOAT,
    [def_sack_yards] FLOAT,
    [def_qb_hits] INT,
    [def_interceptions] INT,
    [def_interception_yards] INT,
    [def_pass_defended] INT,
    [def_tds] INT,
    [def_fumbles] INT,
    [def_safeties] INT,
    [misc_yards] INT,
    [fumble_recovery_own] INT,
    [fumble_recovery_yards_own] INT,
    [fumble_recovery_opp] INT,
    [fumble_recovery_yards_opp] INT,
    [fumble_recovery_tds] INT,
    [penalties] INT,
    [penalty_yards] INT,
    [punt_returns] INT,
    [punt_return_yards] INT,
    [kickoff_returns] INT,
    [kickoff_return_yards] INT,
    [fg_made] INT,
    [fg_att] INT,
    [fg_missed] INT,
    [fg_blocked] INT,
    [fg_long] FLOAT,
    [fg_pct] FLOAT,
    [fg_made_0_19] INT,
    [fg_made_20_29] INT,
    [fg_made_30_39] INT,
    [fg_made_40_49] INT,
    [fg_made_50_59] INT,
    [fg_made_60_] INT,
    [fg_missed_0_19] INT,
    [fg_missed_20_29] INT,
    [fg_missed_30_39] INT,
    [fg_missed_40_49] INT,
    [fg_missed_50_59] INT,
    [fg_missed_60_] INT,
    [fg_made_list] VARCHAR(MAX),
    [fg_missed_list] VARCHAR(MAX),
    [fg_blocked_list] VARCHAR(MAX),
    [fg_made_distance] INT,
    [fg_missed_distance] INT,
    [fg_blocked_distance] INT,
    [pat_made] INT,
    [pat_att] INT,
    [pat_missed] INT,
    [pat_blocked] INT,
    [pat_pct] FLOAT,
    [gwfg_made] INT,
    [gwfg_att] INT,
    [gwfg_missed] INT,
    [gwfg_blocked] INT,
    [gwfg_distance] INT,
    [fantasy_points] FLOAT,
    [fantasy_points_ppr] FLOAT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL
);

CREATE TABLE [nfl].[players] (
    [gsis_id] VARCHAR(MAX),
    [display_name] VARCHAR(MAX),
    [common_first_name] VARCHAR(MAX),
    [first_name] VARCHAR(MAX),
    [last_name] VARCHAR(MAX),
    [short_name] VARCHAR(MAX),
    [football_name] VARCHAR(MAX),
    [suffix] VARCHAR(MAX),
    [esb_id] VARCHAR(MAX),
    [nfl_id] FLOAT,
    [pfr_id] VARCHAR(MAX),
    [pff_id] FLOAT,
    [otc_id] FLOAT,
    [espn_id] FLOAT,
    [smart_id] VARCHAR(MAX),
    [birth_date] DATE,
    [position_group] VARCHAR(MAX),
    [position] VARCHAR(MAX),
    [ngs_position_group] VARCHAR(MAX),
    [ngs_position] VARCHAR(MAX),
    [height_in] FLOAT,
    [weight_lbs] FLOAT,
    [headshot] VARCHAR(MAX),
    [college_name] VARCHAR(MAX),
    [college_conference] VARCHAR(MAX),
    [jersey_number] FLOAT,
    [rookie_season] INT,
    [last_season] INT,
    [latest_team] VARCHAR(MAX),
    [status] VARCHAR(MAX),
    [ngs_status] VARCHAR(MAX),
    [ngs_status_short] VARCHAR(MAX),
    [years_of_experience] INT,
    [pff_position] VARCHAR(MAX),
    [pff_status] VARCHAR(MAX),
    [draft_year] FLOAT,
    [draft_round] FLOAT,
    [draft_pick] FLOAT,
    [draft_team] VARCHAR(MAX),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL
);

CREATE TABLE [nfl].[rosters_weekly] (
    [season] INT,
    [team] VARCHAR(MAX),
    [position] VARCHAR(MAX),
    [depth_chart_position] VARCHAR(MAX),
    [jersey_number] FLOAT,
    [status] VARCHAR(MAX),
    [full_name] VARCHAR(MAX),
    [first_name] VARCHAR(MAX),
    [last_name] VARCHAR(MAX),
    [birth_date] DATE,
    [height_in] FLOAT,
    [weight_lbs] FLOAT,
    [college] VARCHAR(MAX),
    [gsis_id] VARCHAR(MAX),
    [espn_id] FLOAT,
    [sportradar_id] VARCHAR(MAX),
    [yahoo_id] FLOAT,
    [rotowire_id] FLOAT,
    [pff_id] FLOAT,
    [pfr_id] VARCHAR(MAX),
    [fantasy_data_id] FLOAT,
    [sleeper_id] FLOAT,
    [years_exp] INT,
    [headshot_url] VARCHAR(MAX),
    [ngs_position] VARCHAR(MAX),
    [week] INT,
    [game_type] VARCHAR(MAX),
    [status_description_abbr] VARCHAR(MAX),
    [football_name] VARCHAR(MAX),
    [esb_id] VARCHAR(MAX),
    [gsis_it_id] BIGINT,
    [smart_id] VARCHAR(MAX),
    [entry_year] INT,
    [rookie_year] INT,
    [draft_club] VARCHAR(MAX),
    [draft_number] FLOAT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL
);

CREATE TABLE [nfl].[seasons] (
    [season_id] INT NOT NULL,
    [season_year] SMALLINT NOT NULL,
    [season_type] VARCHAR(10) NOT NULL,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_seasons] PRIMARY KEY ([season_id])
);

CREATE TABLE [nfl].[snap_counts] (
    [game_id] VARCHAR(MAX),
    [pfr_game_id] VARCHAR(MAX),
    [season] INT,
    [game_type] VARCHAR(MAX),
    [week] INT,
    [player_name] VARCHAR(MAX),
    [pfr_player_id] VARCHAR(MAX),
    [position] VARCHAR(MAX),
    [team] VARCHAR(MAX),
    [opponent] VARCHAR(MAX),
    [offense_snaps] FLOAT,
    [offense_pct] FLOAT,
    [defense_snaps] FLOAT,
    [defense_pct] FLOAT,
    [st_snaps] FLOAT,
    [st_pct] FLOAT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL
);

CREATE TABLE [nfl].[team_game_stats] (
    [season] INT,
    [week] INT,
    [team] VARCHAR(MAX),
    [season_type] VARCHAR(MAX),
    [opponent_team] VARCHAR(MAX),
    [completions] INT,
    [attempts] INT,
    [passing_yards] INT,
    [passing_tds] INT,
    [passing_interceptions] INT,
    [sacks_suffered] INT,
    [sack_yards_lost] INT,
    [sack_fumbles] INT,
    [sack_fumbles_lost] INT,
    [passing_air_yards] INT,
    [passing_yards_after_catch] INT,
    [passing_first_downs] INT,
    [passing_epa] FLOAT,
    [passing_cpoe] FLOAT,
    [passing_2pt_conversions] INT,
    [carries] INT,
    [rushing_yards] INT,
    [rushing_tds] INT,
    [rushing_fumbles] INT,
    [rushing_fumbles_lost] INT,
    [rushing_first_downs] INT,
    [rushing_epa] FLOAT,
    [rushing_2pt_conversions] INT,
    [receptions] INT,
    [targets] INT,
    [receiving_yards] INT,
    [receiving_tds] INT,
    [receiving_fumbles] INT,
    [receiving_fumbles_lost] INT,
    [receiving_air_yards] INT,
    [receiving_yards_after_catch] INT,
    [receiving_first_downs] INT,
    [receiving_epa] FLOAT,
    [receiving_2pt_conversions] INT,
    [special_teams_tds] INT,
    [def_tackles_solo] INT,
    [def_tackles_with_assist] INT,
    [def_tackle_assists] INT,
    [def_tackles_for_loss] INT,
    [def_tackles_for_loss_yards] INT,
    [def_fumbles_forced] INT,
    [def_sacks] FLOAT,
    [def_sack_yards] FLOAT,
    [def_qb_hits] INT,
    [def_interceptions] INT,
    [def_interception_yards] INT,
    [def_pass_defended] INT,
    [def_tds] INT,
    [def_fumbles] INT,
    [def_safeties] INT,
    [misc_yards] INT,
    [fumble_recovery_own] INT,
    [fumble_recovery_yards_own] INT,
    [fumble_recovery_opp] INT,
    [fumble_recovery_yards_opp] INT,
    [fumble_recovery_tds] INT,
    [penalties] INT,
    [penalty_yards] INT,
    [timeouts] INT,
    [punt_returns] INT,
    [punt_return_yards] INT,
    [kickoff_returns] INT,
    [kickoff_return_yards] INT,
    [fg_made] INT,
    [fg_att] INT,
    [fg_missed] INT,
    [fg_blocked] INT,
    [fg_long] FLOAT,
    [fg_pct] FLOAT,
    [fg_made_0_19] INT,
    [fg_made_20_29] INT,
    [fg_made_30_39] INT,
    [fg_made_40_49] INT,
    [fg_made_50_59] INT,
    [fg_made_60_] INT,
    [fg_missed_0_19] INT,
    [fg_missed_20_29] INT,
    [fg_missed_30_39] INT,
    [fg_missed_40_49] INT,
    [fg_missed_50_59] INT,
    [fg_missed_60_] INT,
    [fg_made_list] VARCHAR(MAX),
    [fg_missed_list] VARCHAR(MAX),
    [fg_blocked_list] VARCHAR(MAX),
    [fg_made_distance] INT,
    [fg_missed_distance] INT,
    [fg_blocked_distance] INT,
    [pat_made] INT,
    [pat_att] INT,
    [pat_missed] INT,
    [pat_blocked] INT,
    [pat_pct] FLOAT,
    [gwfg_made] INT,
    [gwfg_att] INT,
    [gwfg_missed] INT,
    [gwfg_blocked] INT,
    [gwfg_distance] INT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL
);

CREATE TABLE [nfl].[teams] (
    [team_id] INT NOT NULL,
    [name] VARCHAR(100) NOT NULL,
    [abbreviation] VARCHAR(10) NOT NULL,
    [conference] VARCHAR(10) NOT NULL,
    [division] VARCHAR(20) NOT NULL,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_teams] PRIMARY KEY ([team_id])
);
