-- Generated 2026-07-04. Apply in order: common/odds schemas first, then sport schemas.

CREATE TABLE [mlb].[batter_context] (
    [game_date] DATE NOT NULL,
    [game_pk] INT NOT NULL,
    [batter_id] INT NOT NULL,
    [team_id] INT,
    [is_home] BIT,
    [opp_pitcher_id] INT,
    [opp_pitcher_hand] CHAR(1),
    [venue_id] INT,
    [venue_name] NVARCHAR(120),
    [day_night] VARCHAR(10),
    [recent_batting_order] INT,
    [lineup_confirmed] BIT DEFAULT ((0)) NOT NULL,
    [updated_at] DATETIME2 DEFAULT (sysutcdatetime()) NOT NULL,
    CONSTRAINT [PK_batter_context] PRIMARY KEY ([game_date], [game_pk], [batter_id])
);

CREATE TABLE [mlb].[batter_projections] (
    [game_date] DATE NOT NULL,
    [game_pk] INT NOT NULL,
    [batter_id] INT NOT NULL,
    [market_key] VARCHAR(40) NOT NULL,
    [projected_value] FLOAT,
    [confidence] FLOAT,
    [model_version] VARCHAR(20) NOT NULL,
    [updated_at] DATETIME2 DEFAULT (sysutcdatetime()) NOT NULL,
    CONSTRAINT [PK_batter_projections] PRIMARY KEY ([game_date], [game_pk], [batter_id], [market_key])
);

CREATE TABLE [mlb].[batting_stats] (
    [batter_game_id] VARCHAR(30) NOT NULL,
    [game_pk] INT NOT NULL,
    [game_date] DATE,
    [player_id] INT NOT NULL,
    [team_id] INT NOT NULL,
    [side] CHAR(1),
    [position] VARCHAR(10),
    [batting_order] SMALLINT,
    [at_bats] SMALLINT,
    [runs] SMALLINT,
    [hits] SMALLINT,
    [doubles] SMALLINT,
    [triples] SMALLINT,
    [home_runs] SMALLINT,
    [rbi] SMALLINT,
    [stolen_bases] SMALLINT,
    [walks] SMALLINT,
    [strikeouts] SMALLINT,
    [left_on_base] SMALLINT,
    [batting_avg] DECIMAL(6,3),
    [obp] DECIMAL(6,3),
    [slg] DECIMAL(6,3),
    [ops] DECIMAL(6,3),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    [fly_outs] INT,
    [ground_outs] INT,
    [air_outs] INT,
    [pop_outs] INT,
    [line_outs] INT,
    [total_bases] INT,
    [games_played] INT,
    [plate_appearances] INT,
    [intentional_walks] INT,
    [hit_by_pitch] INT,
    [sac_bunts] INT,
    [sac_flies] INT,
    CONSTRAINT [PK_batting_stats] PRIMARY KEY ([batter_game_id])
);
CREATE INDEX [IX_batting_stats_game_pk] ON [mlb].[batting_stats] ([game_pk]);

CREATE TABLE [mlb].[career_batter_vs_pitcher] (
    [batter_id] INT NOT NULL,
    [pitcher_id] INT NOT NULL,
    [plate_appearances] INT NOT NULL,
    [at_bats] INT NOT NULL,
    [hits] INT NOT NULL,
    [singles] INT NOT NULL,
    [doubles] INT NOT NULL,
    [triples] INT NOT NULL,
    [home_runs] INT NOT NULL,
    [rbi] INT NOT NULL,
    [walks] INT NOT NULL,
    [strikeouts] INT NOT NULL,
    [hit_by_pitch] INT NOT NULL,
    [sac_flies] INT NOT NULL,
    [total_bases] INT NOT NULL,
    [batting_avg] DECIMAL(5,3),
    [obp] DECIMAL(5,3),
    [slg] DECIMAL(5,3),
    [ops] DECIMAL(5,3),
    [last_faced_date] DATE,
    [updated_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    [bbe] INT,
    [avg_ev] DECIMAL(5,1),
    [avg_la] DECIMAL(5,1),
    [avg_dist] DECIMAL(6,1),
    [avg_xba] DECIMAL(5,3),
    [hard_hit_ct] INT,
    [barrel_ct] INT,
    CONSTRAINT [PK_career_batter_vs_pitcher] PRIMARY KEY ([batter_id], [pitcher_id])
);
CREATE INDEX [IX_bvp_pitcher] ON [mlb].[career_batter_vs_pitcher] ([pitcher_id], [batter_id]);

CREATE TABLE [mlb].[daily_lineups] (
    [game_pk] INT NOT NULL,
    [team_id] INT NOT NULL,
    [player_id] INT NOT NULL,
    [game_date] DATE NOT NULL,
    [batting_order] INT NOT NULL,
    [position] VARCHAR(5),
    [is_confirmed] BIT DEFAULT ((1)) NOT NULL,
    [source] VARCHAR(20) DEFAULT ('lineups-hydrate') NOT NULL,
    [updated_at] DATETIME2 DEFAULT (sysutcdatetime()) NOT NULL,
    CONSTRAINT [PK_daily_lineups] PRIMARY KEY ([game_pk], [team_id], [player_id])
);
CREATE INDEX [IX_daily_lineups_date] ON [mlb].[daily_lineups] ([game_date]);

CREATE TABLE [mlb].[games] (
    [game_pk] INT NOT NULL,
    [game_date] DATE NOT NULL,
    [game_datetime] DATETIME2,
    [game_type] CHAR(1) DEFAULT ('R') NOT NULL,
    [game_status] VARCHAR(20),
    [abstract_game_state] VARCHAR(20),
    [day_night] VARCHAR(10),
    [double_header] CHAR(1),
    [game_number] TINYINT,
    [game_display] VARCHAR(20),
    [venue_id] INT,
    [venue_name] VARCHAR(100),
    [away_team_id] INT NOT NULL,
    [away_team_score] TINYINT,
    [away_is_winner] BIT,
    [away_pitcher_id] INT,
    [away_pitcher_name] VARCHAR(100),
    [away_pitcher_hand] CHAR(1),
    [home_team_id] INT NOT NULL,
    [home_team_score] TINYINT,
    [home_is_winner] BIT,
    [home_pitcher_id] INT,
    [home_pitcher_name] VARCHAR(100),
    [home_pitcher_hand] CHAR(1),
    [is_tie] BIT,
    [games_in_series] TINYINT,
    [series_game_number] TINYINT,
    [game_date_index] SMALLINT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_games] PRIMARY KEY ([game_pk])
);

CREATE TABLE [mlb].[pitcher_season_stats] (
    [pitcher_season_id] INT NOT NULL,
    [player_id] INT NOT NULL,
    [player_name] VARCHAR(100),
    [team_id] INT,
    [season_year] SMALLINT NOT NULL,
    [age] TINYINT,
    [games_played] SMALLINT,
    [games_started] SMALLINT,
    [ground_outs] SMALLINT,
    [air_outs] SMALLINT,
    [runs_allowed] SMALLINT,
    [doubles_allowed] SMALLINT,
    [triples_allowed] SMALLINT,
    [hr_allowed] SMALLINT,
    [strikeouts] SMALLINT,
    [walks] SMALLINT,
    [intentional_walks] SMALLINT,
    [hits_allowed] SMALLINT,
    [hit_by_pitch] SMALLINT,
    [batting_avg_against] DECIMAL(5,3),
    [at_bats_faced] SMALLINT,
    [obp_against] DECIMAL(5,3),
    [slg_against] DECIMAL(5,3),
    [ops_against] DECIMAL(5,3),
    [caught_stealing] SMALLINT,
    [stolen_bases_allowed] SMALLINT,
    [stolen_base_pct_against] DECIMAL(5,3),
    [caught_stealing_pct] DECIMAL(5,3),
    [ground_into_double_play] SMALLINT,
    [total_pitches] INT,
    [era] DECIMAL(6,2),
    [innings_pitched] DECIMAL(6,3),
    [wins] SMALLINT,
    [losses] SMALLINT,
    [saves] SMALLINT,
    [save_opportunities] SMALLINT,
    [holds] SMALLINT,
    [blown_saves] SMALLINT,
    [earned_runs] SMALLINT,
    [whip] DECIMAL(5,2),
    [batters_faced] SMALLINT,
    [outs_recorded] INT,
    [games_pitched] SMALLINT,
    [complete_games] SMALLINT,
    [shutouts] SMALLINT,
    [strikes_thrown] INT,
    [strike_pct] DECIMAL(5,3),
    [hit_batsmen] SMALLINT,
    [balks] SMALLINT,
    [wild_pitches] SMALLINT,
    [pickoffs] SMALLINT,
    [total_bases_allowed] SMALLINT,
    [ground_outs_to_air_outs] DECIMAL(5,2),
    [win_pct] DECIMAL(5,3),
    [pitches_per_inning] DECIMAL(6,2),
    [games_finished] SMALLINT,
    [strikeout_walk_ratio] DECIMAL(6,2),
    [k_per_9] DECIMAL(6,2),
    [bb_per_9] DECIMAL(6,2),
    [h_per_9] DECIMAL(6,2),
    [runs_per_9] DECIMAL(6,2),
    [hr_per_9] DECIMAL(6,2),
    [inherited_runners] SMALLINT,
    [inherited_runners_scored] SMALLINT,
    [catchers_interference] SMALLINT,
    [sac_bunts] SMALLINT,
    [sac_flies] SMALLINT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pitcher_season_stats] PRIMARY KEY ([pitcher_season_id])
);

CREATE TABLE [mlb].[pitching_stats] (
    [pitcher_game_id] VARCHAR(30) NOT NULL,
    [game_pk] INT NOT NULL,
    [game_date] DATE NOT NULL,
    [player_id] INT NOT NULL,
    [team_id] INT NOT NULL,
    [side] CHAR(1),
    [innings_pitched] DECIMAL(6,3),
    [hits_allowed] SMALLINT,
    [runs_allowed] SMALLINT,
    [earned_runs] SMALLINT,
    [walks] SMALLINT,
    [strikeouts] SMALLINT,
    [hr_allowed] SMALLINT,
    [era] DECIMAL(6,2),
    [pitches] SMALLINT,
    [strikes] SMALLINT,
    [note] VARCHAR(50),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_pitching_stats] PRIMARY KEY ([pitcher_game_id])
);
CREATE INDEX [IX_pitching_stats_game_pk] ON [mlb].[pitching_stats] ([game_pk]);

CREATE TABLE [mlb].[play_by_play] (
    [play_event_id] VARCHAR(50) NOT NULL,
    [game_pk] INT NOT NULL,
    [game_date] DATE,
    [at_bat_number] INT,
    [play_event_index] INT,
    [inning] INT,
    [is_top_inning] BIT,
    [team_id] INT,
    [vs_team_id] INT,
    [away_team_id] INT,
    [home_team_id] INT,
    [venue_id] INT,
    [result_event_type] VARCHAR(50),
    [result_description] VARCHAR(1000),
    [result_rbi] INT,
    [result_is_out] BIT,
    [at_bat_is_complete] BIT,
    [at_bat_is_scoring_play] BIT,
    [at_bat_has_out] BIT,
    [at_bat_end_time] DATETIME2,
    [play_end_time] DATETIME2,
    [batter_id] INT,
    [batter_hand_code] CHAR(1),
    [batter_split] VARCHAR(30),
    [pitcher_id] INT,
    [pitcher_hand_code] CHAR(1),
    [pitcher_split] VARCHAR(30),
    [play_id] VARCHAR(50),
    [play_event_type] VARCHAR(30),
    [is_pitch] BIT,
    [is_base_running_play] BIT,
    [pitch_number] INT,
    [pitch_call_code] VARCHAR(5),
    [pitch_type_code] VARCHAR(5),
    [play_event_description] VARCHAR(1000),
    [is_hit_into_play] BIT,
    [is_strike] BIT,
    [is_ball] BIT,
    [is_out] BIT,
    [runner_going] BIT,
    [count_balls_strikes] VARCHAR(5),
    [count_outs] INT,
    [is_last_pitch] BIT,
    [is_at_bat] BIT,
    [is_plate_appearance] BIT,
    [play_event_end_time] DATETIME2,
    [pitch_start_speed] DECIMAL(5,1),
    [pitch_end_speed] DECIMAL(5,1),
    [pitch_zone] INT,
    [strike_zone_top] DECIMAL(5,2),
    [strike_zone_bottom] DECIMAL(5,2),
    [hit_launch_speed] DECIMAL(5,1),
    [hit_launch_angle] INT,
    [hit_total_distance] INT,
    [hit_trajectory] VARCHAR(30),
    [hit_hardness] VARCHAR(20),
    [hit_location] INT,
    [hit_probability] DECIMAL(5,2),
    [hit_bat_speed] DECIMAL(5,1),
    [home_run_ballparks] INT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_play_by_play] PRIMARY KEY ([play_event_id])
);
CREATE INDEX [IX_play_by_play_game_pk] ON [mlb].[play_by_play] ([game_pk]);

CREATE TABLE [mlb].[player_at_bats] (
    [at_bat_id] VARCHAR(30) NOT NULL,
    [game_pk] INT NOT NULL,
    [game_date] DATE,
    [at_bat_number] INT NOT NULL,
    [inning] INT,
    [is_top_inning] BIT,
    [batter_id] INT,
    [pitcher_id] INT,
    [result_event_type] VARCHAR(50),
    [result_description] VARCHAR(1000),
    [result_rbi] INT,
    [hit_launch_speed] DECIMAL(5,1),
    [hit_launch_angle] INT,
    [hit_total_distance] INT,
    [hit_trajectory] VARCHAR(30),
    [hit_hardness] VARCHAR(20),
    [hit_probability] DECIMAL(5,2),
    [hit_bat_speed] DECIMAL(5,1),
    [home_run_ballparks] INT,
    [away_team_id] INT,
    [home_team_id] INT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_player_at_bats] PRIMARY KEY ([at_bat_id])
);
CREATE INDEX [IX_player_at_bats_batter] ON [mlb].[player_at_bats] ([batter_id], [game_date]);
CREATE INDEX [IX_player_at_bats_game_pk] ON [mlb].[player_at_bats] ([game_pk]);

CREATE TABLE [mlb].[player_game_statcast] (
    [batter_id] INT NOT NULL,
    [game_pk] INT NOT NULL,
    [game_date] DATE,
    [team_id] INT,
    [opp_team_id] INT,
    [opp_pitcher_id] INT,
    [is_home] BIT,
    [pa] INT,
    [ab] INT,
    [hits] INT,
    [singles] INT,
    [doubles] INT,
    [triples] INT,
    [home_runs] INT,
    [xbh] INT,
    [total_bases] INT,
    [runs] INT,
    [rbi] INT,
    [strikeouts] INT,
    [walks] INT,
    [hit_by_pitch] INT,
    [sac_flies] INT,
    [hip] INT,
    [bbe] INT,
    [ev_sum] FLOAT,
    [avg_ev] DECIMAL(5,1),
    [max_ev] DECIMAL(5,1),
    [la_cnt] INT,
    [la_sum] FLOAT,
    [avg_la] DECIMAL(5,1),
    [dist_cnt] INT,
    [dist_sum] FLOAT,
    [avg_dist] DECIMAL(6,1),
    [xba_cnt] INT,
    [xba_sum] FLOAT,
    [avg_xba] DECIMAL(5,3),
    [hard_hit] INT,
    [barrels] INT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_player_game_statcast] PRIMARY KEY ([batter_id], [game_pk])
);
CREATE INDEX [IX_player_game_statcast_date] ON [mlb].[player_game_statcast] ([game_date], [batter_id]);
CREATE INDEX [IX_player_game_statcast_game] ON [mlb].[player_game_statcast] ([game_pk]);

CREATE TABLE [mlb].[player_patterns] (
    [batter_id] INT NOT NULL,
    [as_of_date] DATE NOT NULL,
    [season] INT NOT NULL,
    [games_played] INT,
    [hr_games] INT,
    [games_since_hr] INT,
    [pattern_samples] INT,
    [pattern_repeats] INT,
    [pattern_hit_rate] DECIMAL(5,3),
    [hr_pattern_early] DECIMAL(5,3),
    [hr_pattern_late] DECIMAL(5,3),
    [hr_hot] BIT DEFAULT ((0)) NOT NULL,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_player_patterns] PRIMARY KEY ([batter_id], [as_of_date])
);
CREATE INDEX [IX_player_patterns_date] ON [mlb].[player_patterns] ([as_of_date], [batter_id]);

CREATE TABLE [mlb].[player_season_batting] (
    [player_season_id] INT NOT NULL,
    [player_id] INT NOT NULL,
    [player_name] VARCHAR(100),
    [team_id] INT,
    [season_year] SMALLINT NOT NULL,
    [age] TINYINT,
    [games_played] SMALLINT,
    [at_bats] SMALLINT,
    [plate_appearances] SMALLINT,
    [hits] SMALLINT,
    [doubles] SMALLINT,
    [triples] SMALLINT,
    [home_runs] SMALLINT,
    [runs] SMALLINT,
    [rbi] SMALLINT,
    [walks] SMALLINT,
    [intentional_walks] SMALLINT,
    [strikeouts] SMALLINT,
    [hit_by_pitch] SMALLINT,
    [stolen_bases] SMALLINT,
    [caught_stealing] SMALLINT,
    [stolen_base_pct] DECIMAL(5,3),
    [caught_stealing_pct] DECIMAL(5,3),
    [ground_into_double_play] SMALLINT,
    [total_bases] SMALLINT,
    [left_on_base] SMALLINT,
    [sac_bunts] SMALLINT,
    [sac_flies] SMALLINT,
    [ground_outs] SMALLINT,
    [air_outs] SMALLINT,
    [pitches_seen] INT,
    [batting_avg] DECIMAL(5,3),
    [obp] DECIMAL(5,3),
    [slg] DECIMAL(5,3),
    [ops] DECIMAL(5,3),
    [babip] DECIMAL(5,3),
    [ground_outs_to_air_outs] DECIMAL(5,2),
    [at_bats_per_hr] DECIMAL(6,2),
    [catchers_interference] SMALLINT,
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_player_season_batting] PRIMARY KEY ([player_season_id])
);

CREATE TABLE [mlb].[player_trend_stats] (
    [batter_id] INT NOT NULL,
    [game_date] DATE NOT NULL,
    [w10_pa] INT,
    [w10_ab] INT,
    [w10_hits] INT,
    [w10_hit_rate] DECIMAL(5,3),
    [w10_bb_rate] DECIMAL(5,3),
    [w10_k_rate] DECIMAL(5,3),
    [w10_total_bases] INT,
    [w10_tb_per_pa] DECIMAL(5,3),
    [w10_home_runs] INT,
    [w10_avg_ev] DECIMAL(5,1),
    [w10_hard_hit_pct] DECIMAL(5,3),
    [w10_barrel_pct] DECIMAL(5,3),
    [w10_avg_xba] DECIMAL(5,3),
    [w30_pa] INT,
    [w30_ab] INT,
    [w30_hits] INT,
    [w30_hit_rate] DECIMAL(5,3),
    [w30_bb_rate] DECIMAL(5,3),
    [w30_k_rate] DECIMAL(5,3),
    [w30_total_bases] INT,
    [w30_tb_per_pa] DECIMAL(5,3),
    [w30_home_runs] INT,
    [w30_avg_ev] DECIMAL(5,1),
    [w30_hard_hit_pct] DECIMAL(5,3),
    [w30_barrel_pct] DECIMAL(5,3),
    [w30_avg_xba] DECIMAL(5,3),
    [w60_pa] INT,
    [w60_ab] INT,
    [w60_hits] INT,
    [w60_hit_rate] DECIMAL(5,3),
    [w60_bb_rate] DECIMAL(5,3),
    [w60_k_rate] DECIMAL(5,3),
    [w60_total_bases] INT,
    [w60_tb_per_pa] DECIMAL(5,3),
    [w60_home_runs] INT,
    [w60_avg_ev] DECIMAL(5,1),
    [w60_hard_hit_pct] DECIMAL(5,3),
    [w60_barrel_pct] DECIMAL(5,3),
    [w60_avg_xba] DECIMAL(5,3),
    [vs_lhp_pa] INT,
    [vs_lhp_hits] INT,
    [vs_lhp_hit_rate] DECIMAL(5,3),
    [vs_rhp_pa] INT,
    [vs_rhp_hits] INT,
    [vs_rhp_hit_rate] DECIMAL(5,3),
    [home_pa] INT,
    [home_hits] INT,
    [home_hit_rate] DECIMAL(5,3),
    [away_pa] INT,
    [away_hits] INT,
    [away_hit_rate] DECIMAL(5,3),
    [updated_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    [vs_lhp_xbh] INT,
    [vs_lhp_avg_ev] DECIMAL(5,1),
    [vs_lhp_hard_hit_pct] DECIMAL(5,3),
    [vs_lhp_avg_xba] DECIMAL(5,3),
    [vs_lhp_babip] DECIMAL(5,3),
    [vs_rhp_xbh] INT,
    [vs_rhp_avg_ev] DECIMAL(5,1),
    [vs_rhp_hard_hit_pct] DECIMAL(5,3),
    [vs_rhp_avg_xba] DECIMAL(5,3),
    [vs_rhp_babip] DECIMAL(5,3),
    CONSTRAINT [PK_player_trend_stats] PRIMARY KEY ([batter_id], [game_date])
);
CREATE INDEX [IX_trend_stats_date] ON [mlb].[player_trend_stats] ([game_date], [batter_id]);

CREATE TABLE [mlb].[players] (
    [player_id] INT NOT NULL,
    [player_name] VARCHAR(100) NOT NULL,
    [team_id] INT,
    [position] VARCHAR(10),
    [bat_side] CHAR(1),
    [pitch_hand] CHAR(1),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    [last_seen_season] INT DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_players] PRIMARY KEY ([player_id])
);

CREATE TABLE [mlb].[teams] (
    [team_id] INT NOT NULL,
    [team_abbreviation] VARCHAR(10) NOT NULL,
    [full_name] VARCHAR(100),
    [venue_id] INT,
    [ballpark_pal_team] VARCHAR(10),
    [created_at] DATETIME2 DEFAULT (getutcdate()) NOT NULL,
    CONSTRAINT [PK_teams] PRIMARY KEY ([team_id])
);
