name: Grades Migration v2

on:
  workflow_dispatch:

env:
  SQL_TRUST_CERT: "yes"
  PYTHONPATH: /Users/schnapp/code/schnapp-bet

jobs:
  migrate:
    runs-on: [self-hosted, mac-runner]
    steps:
      - uses: actions/checkout@v4


      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SQL_DATABASE: op://web-variables/Database/database
          SQL_PASSWORD: op://web-variables/Database/password
          SQL_SERVER: op://web-variables/Database/server
          SQL_USERNAME: op://web-variables/Database/username
      - name: Activate virtualenv
        run: echo "$HOME/venv/bin" >> $GITHUB_PATH

      - name: Run migration
        run: python grading/migrate_grades_v2.py
